# Generated by Django 4.1.3 on 2022-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20),
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(choices=[('1', '12:00 AM - 01:00 AM'), ('2', '01:00 AM - 02:00 AM'), ('3', '02:00 AM - 03:00 AM'), ('4', '03:00 AM - 04:00 AM'), ('5', '04:00 AM - 05:00 AM'), ('6', '05:00 AM - 06:00 AM'), ('7', '06:00 AM - 07:00 AM'), ('8', '07:00 AM - 08:00 AM'), ('9', '08:00 AM - 09:00 AM'), ('10', '09:00 AM - 10:00 AM'), ('11', '10:00 AM - 11:00 AM'), ('12', '11:00 AM - 12:00 AM'), ('13', '12:00 PM - 01:00 PM'), ('14', '01:00 PM - 02:00 PM'), ('15', '02:00 PM - 03:00 PM'), ('16', '03:00 PM - 04:00 PM'), ('17', '04:00 PM - 05:00 PM'), ('18', '05:00 PM - 06:00 PM'), ('19', '06:00 PM - 07:00 PM'), ('20', '07:00 PM - 08:00 PM'), ('21', '08:00 PM - 09:00 PM'), ('22', '09:00 PM - 10:00 PM'), ('23', '10:00 PM - 11:00 PM'), ('24', '11:00 PM - 12:00 PM')], max_length=100)),
                ('total_seat', models.IntegerField()),
                ('seat_availability', models.IntegerField()),
                ('is_close', models.BooleanField()),
                ('day', models.ManyToManyField(to='schedule.schedule')),
            ],
        ),
    ]
