# Generated by Django 4.1.3 on 2022-12-03 09:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_day_timeslot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schedule',
            managers=[
                ('schedules', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timeslot',
            managers=[
                ('timeslots', django.db.models.manager.Manager()),
            ],
        ),
    ]
