# Generated by Django 4.1.3 on 2022-12-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_managers_alter_timeslot_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeslots',
            field=models.ManyToManyField(to='schedule.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_range',
            field=models.CharField(choices=[('12:00 AM - 01:00 AM', '12:00 AM - 01:00 AM'), ('01:00 AM - 02:00 AM', '01:00 AM - 02:00 AM'), ('02:00 AM - 03:00 AM', '02:00 AM - 03:00 AM'), ('03:00 AM - 04:00 AM', '03:00 AM - 04:00 AM'), ('04:00 AM - 05:00 AM', '04:00 AM - 05:00 AM'), ('05:00 AM - 06:00 AM', '05:00 AM - 06:00 AM'), ('06:00 AM - 07:00 AM', '06:00 AM - 07:00 AM'), ('07:00 AM - 08:00 AM', '07:00 AM - 08:00 AM'), ('08:00 AM - 09:00 AM', '08:00 AM - 09:00 AM'), ('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 AM', '11:00 AM - 12:00 AM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('01:00 PM - 02:00 PM', '01:00 PM - 02:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM - 04:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('05:00 PM - 06:00 PM', '05:00 PM - 06:00 PM'), ('06:00 PM - 07:00 PM', '06:00 PM - 07:00 PM'), ('07:00 PM - 08:00 PM', '07:00 PM - 08:00 PM'), ('08:00 PM - 09:00 PM', '08:00 PM - 09:00 PM'), ('09:00 PM - 10:00 PM', '09:00 PM - 10:00 PM'), ('10:00 PM - 11:00 PM', '10:00 PM - 11:00 PM'), ('11:00 PM - 12:00 PM', '11:00 PM - 12:00 PM')], max_length=100),
        ),
    ]
