# Generated by Django 4.1.3 on 2022-12-07 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_timeslot_day_schedule_timeslots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time_range',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='total_seat',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='SUNDAY', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_start',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_stop',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='seat_availability',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
