# Generated by Django 4.1.3 on 2022-12-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_timeslot_time_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='total_seat',
            field=models.IntegerField(default=20),
        ),
    ]
