# Generated by Django 4.1.3 on 2022-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            managers=[
                ('customers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('timeslot', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=30)),
                ('customerR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageresorder.customer')),
            ],
            managers=[
                ('reservations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            managers=[
                ('restaurants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='reservationC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageresorder.reservation'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('reservationO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manageresorder.reservation')),
                ('customerO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageresorder.customer')),
            ],
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
    ]
