# Generated by Django 4.1.3 on 2022-12-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageresorder', '0002_remove_reservation_customername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reservationC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageresorder.reservation'),
        ),
    ]
