# Generated by Django 4.1.3 on 2022-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
