# Generated by Django 4.1.3 on 2022-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='total_seat',
            new_name='seat_availability',
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_seat',
            field=models.IntegerField(default=0),
        ),
    ]
