# Generated by Django 4.1.3 on 2022-12-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_total_seat_timeslot_seat_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
