# Generated by Django 4.1.3 on 2022-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timeslots',
            field=models.ManyToManyField(to='reservation.timeslot'),
        ),
    ]
