# Generated by Django 4.1.3 on 2022-12-03 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_restaurant_timeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
            ],
            managers=[
                ('fnbs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='fnb',
            field=models.ManyToManyField(to='reservation.fnb'),
        ),
    ]
