# Generated by Django 4.1.3 on 2022-12-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_fnb_remove_order_customer_reservation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
