# Generated by Django 4.1.3 on 2022-12-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='timeslots',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslots', models.ManyToManyField(to='reservation.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.schedule'),
        ),
    ]
