# Generated by Django 4.1.3 on 2022-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_remove_restaurant_timeslots_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
