# Generated by Django 4.1.3 on 2022-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='schedule',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ManyToManyField(to='reservation.schedule'),
        ),
    ]
