# Generated by Django 4.1.3 on 2022-12-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_restaurant_schedule_restaurant_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='schedule',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.schedule'),
        ),
    ]
