# Generated by Django 4.1.3 on 2022-12-10 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FnB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Beverage', 'Beverage')], max_length=15, null=True)),
                ('description', models.TextField(default='', max_length=150)),
            ],
            options={
                'db_table': 'fnb',
            },
            managers=[
                ('fnbs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=30)),
                ('foods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managemenu.fnb')),
            ],
        ),
    ]
