# Generated by Django 4.1.3 on 2022-12-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnb',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='fnb',
            table='fnb',
        ),
    ]
