# Generated by Django 4.1.3 on 2022-12-03 17:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('managemenu', '0002_alter_fnb_name_alter_fnb_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fnb',
            managers=[
                ('fnbs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='fnb',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
