# Generated by Django 4.1.3 on 2022-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenu', '0004_alter_fnb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnb',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
