# Generated by Django 4.1.3 on 2022-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenu', '0006_alter_fnb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnb',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
