# Generated by Django 4.1.3 on 2022-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenu', '0007_alter_fnb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnb',
            name='is_food',
        ),
        migrations.AddField(
            model_name='fnb',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Beverage', 'Beverage')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fnb',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fnb',
            name='price',
            field=models.IntegerField(),
        ),
    ]
