# Generated by Django 4.1.3 on 2022-12-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_restaurant_reservation_order_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fnb',
        ),
        migrations.CreateModel(
            name='FnbChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fnb', models.ManyToManyField(to='order.fnb')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
