# Generated by Django 4.1.3 on 2022-12-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_fnb_fnbchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnbchoice',
            name='fnb',
        ),
        migrations.AddField(
            model_name='fnbchoice',
            name='fnb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.fnb'),
        ),
    ]
