# Generated by Django 4.1.3 on 2022-12-04 10:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fnbchoice',
            managers=[
                ('fnbchoices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('reservations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('restaurants', django.db.models.manager.Manager()),
            ],
        ),
    ]
